export const HEADER_LINE_HEIGHT = '40px'
export const HEADER_LINE_HEIGHT_MOBILE = '28px'

// [DOCUMENT]
export const DOCUMENT_HEADING_HEIGHT = 62
export const DOCUMENT_HEADING_MOBILE_HEIGHT = 54

export const MOBILE_HEADING_DOCUMENT_SCROLLING_HEIGHT = 55
export const MOBILE_HEADING_DOCUMENT_NOT_SCROLLING_HEIGHT = 55

// [DASHBOARD]
export const NAVBAR_DASHBOARD_HEADING_HEIGHT = 157
export const NAVBAR_DASHBOARD_HEADING_MOBILE_HEIGHT = 52

// [PUBLIC]
// includes header and lines
export const NAVBAR_PUBLIC_HEADING_HEIGHT = 84
