export const ZINDEX_ZIPPING_FOLDER_POPUP = 3001
export const ZINDEX_PUBLIC_HEADER = 1299
export const ZINDEX_DOCUMENT_HEADER = 1002
export const ZINDEX_SPASH_SCREEN = 2000
export const ZINDEX_BTN_COPY_CODE = 1000
export const ZINDEX_TOAST_NOTIFY = 1400

export const ZINDEX_COPY_TEXT = 5001
